title = "karpra"

[author]
name = "Karthik Prabhakar"
image = "profile.jpg"
headline = "my tech rambling"
bio = "A little bit about me"
links = [
  { linkedin = "https://www.linkedin.com/in/karpra/"},
  { github  = "https://github.com/karpra" }
]