title = "karpra"

[author]
name = "Karthik Prabhakar"
image = "img/author.jpg"
headline = "A generally awesome human"
bio = "A little bit about me"
links = [
  { linkedin = "https://www.linkedin.com/in/karpra/" }
]